name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]    
  workflow_dispatch:  
    branches: [ main ]    

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2      
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        tag_prefix: release/v
        create_annotated_tag: true
        dry_run: true
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -c release -p:version=${{ steps.tag_version.outputs.new_version }}
    - name: Pack
      run: dotnet pack --no-build --include-symbols -o out -c release -p:version=${{ steps.tag_version.outputs.new_version }}
    - name: Create a GitHub release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.tag_version.outputs.new_tag }}
        release_name: Release ${{ steps.tag_version.outputs.new_version }}
        body: ${{ steps.tag_version.outputs.changelog }}
